# -*- coding: utf-8 -*-
"""374. Guess Number Higher or Lower

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zr_PNyGJACxqiKnCBLrDP4HPoKxrjOC-
"""

class Solution:
    def guessNumber(self, n: int) -> int:
        
        l = 0
        r = n
        while(l<=r):
            mid = (l+r)//2
            k = guess(mid)
            if k ==0:
                return mid
            elif k==-1:
                r=mid-1
            else:
                l = mid+1